# Generated by Django 5.2.7 on 2026-07-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('pcb', '0017_attribute_in_part_number_alter_attributegroup_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(max_length=4000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('total_net_price', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='ارزش خالص')),
                ('total_discount', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='تخفیف کل')),
                ('total_tax', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='مالیات کل')),
                ('total_addition', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='اضافات کل')),
                ('total_price', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='قابل پرداخت')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinvoices', to='accounting.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='PreInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('row_net_price', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='قیمت ردیف')),
                ('row_discount', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='تخفیف ردیف')),
                ('row_tax', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='مالیات ردیف')),
                ('row_addition', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='اضافات ردیف')),
                ('row_price', models.DecimalField(decimal_places=4, max_digits=25, verbose_name='قابل پرداخت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preinvoiceitems', to='pcb.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_for', models.TextField(blank=True, max_length=1000, null=True, verbose_name='اگر تامین کننده فقط بخش خاصی از سفارش را تامین میکند در این بخش درج کنید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordersuppliers', to='pcb.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplierorders', to='sls.supplier')),
            ],
        ),
    ]
