# Generated by Django 5.2.7 on 2026-07-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0002_alter_supplier_options_ordersupplier_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersupplier',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='preinvoice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='preinvoiceitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id']},
        ),
    ]
