# Generated by Django 5.2.7 on 2025-10-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام سیستمی و انگلیسی (مثال: pcb_specifications)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='نام نمایشی برای کاربر (مثال: مشخصات PCB)', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش گروه')),
            ],
            options={
                'verbose_name': 'گروه ویژگی',
                'verbose_name_plural': 'گروه\u200cهای ویژگی',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام سیستمی (مثال: pcb_color)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='نام نمایشی (مثال: رنگ برد)', max_length=255)),
                ('control_type', models.CharField(choices=[('text_input', 'ورودی متنی/عددی'), ('radio_button', 'دکمه رادیویی'), ('select_box', 'لیست کشویی'), ('color_picker', 'انتخابگر رنگ')], default='radio_button', max_length=20, verbose_name='نوع کنترل در فرم')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش ویژگی در گروه')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='pcb.attributegroup', verbose_name='گروه ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['group__display_order', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='مقدار واقعی (مثال: #008000 یا 1.6mm)', max_length=100)),
                ('display_name', models.CharField(help_text='نام نمایشی (مثال: سبز)', max_length=255)),
                ('is_default', models.BooleanField(default=False, verbose_name='گزینه پیش\u200cفرض؟')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش گزینه')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pcb.attribute', verbose_name='ویژگی مربوطه')),
            ],
            options={
                'verbose_name': 'گزینه ویژگی',
                'verbose_name_plural': 'گزینه\u200cهای ویژگی',
                'ordering': ['display_order'],
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
