# Generated by Django 5.2.7 on 2025-10-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pcb', '0002_order_orderselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='یک نام توصیفی برای این قانون', max_length=255)),
                ('action_type', models.CharField(choices=[('disable', 'غیرفعال کردن (Disable)'), ('hide', 'مخفی کردن (Hide)'), ('enable', 'فعال کردن (Enable)'), ('show', 'نمایش دادن (Show)')], max_length=10, verbose_name='نوع عمل')),
                ('target_object_id', models.PositiveIntegerField(verbose_name='شناسه آبجکت هدف')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع مدل هدف')),
                ('trigger_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_rules', to='pcb.attributeoption', verbose_name='گزینه فعال\u200cکننده')),
            ],
            options={
                'verbose_name': 'قانون شرطی',
                'verbose_name_plural': 'قوانین شرطی',
            },
        ),
    ]
