# Generated by Django 5.2.7 on 2025-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0003_conditionalrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/'),
        ),
    ]
