# Generated by Django 5.2.7 on 2025-10-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0004_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
