# Generated by Django 5.2.7 on 2025-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0005_order_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='for_assemble',
            field=models.BooleanField(default=False),
        ),
    ]
