# Generated by Django 5.2.7 on 2025-10-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0006_attributegroup_for_assemble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributegroup',
            name='for_assemble',
        ),
    ]
