# Generated by Django 5.2.7 on 2025-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0007_remove_attributegroup_for_assemble'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/attribute/image/'),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/attribute_group/image/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/orders/files/'),
        ),
    ]
