# Generated by Django 5.2.7 on 2025-10-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0008_attribute_file_attributegroup_file_alter_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/attribute/image/'),
        ),
    ]
