# Generated by Django 5.2.7 on 2025-10-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_managers'),
        ('pcb', '0009_attributeoption_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='guid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guids', to='blog.post'),
        ),
    ]
