# Generated by Django 5.2.7 on 2025-10-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0010_attribute_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReadOnly',
            fields=[
            ],
            options={
                'verbose_name': 'Order (View Only)',
                'verbose_name_plural': 'Orders (View Only)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pcb.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
