# Generated by Django 5.2.7 on 2025-10-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0011_orderreadonly_order_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
