# Generated by Django 5.2.7 on 2025-10-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0012_order_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
