# Generated by Django 5.2.7 on 2025-10-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0013_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to='upload/orders/quotation/files/'),
        ),
    ]
