# Generated by Django 5.2.7 on 2025-11-02 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0014_order_quotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('quotation', 'پیش فاکتور شده (در انتظار پرداخت)'), ('process', 'در حال ساخت'), ('pending_delivery', 'در انتظار تحویل'), ('deliver', 'تحویل شده'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/orders/payment/files/')),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_creator_%(model_name)s', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_editor_%(model_name)s', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='pcb.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
