# Generated by Django 5.2.7 on 2026-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0015_alter_order_status_orderpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='part_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attribute/image/'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attribute_group/image/'),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/attribute/image/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/files/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quotation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/quotation/files/'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/payment/files/'),
        ),
    ]
