# Generated by Django 5.2.7 on 2026-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0016_order_part_number_alter_attribute_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='in_part_number',
            field=models.BooleanField(default=False, verbose_name='نمایش در پارت نامبر؟'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='name',
            field=models.CharField(help_text='نام سیستمی و انگلیسی (مثال: pcb_specifications) به عنوان پیشوند سفارش ذخیره میشود', max_length=100, unique=True),
        ),
    ]
