# Generated by Django 5.2.7 on 2026-07-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0017_attribute_in_part_number_alter_attributegroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام سیستمی و انگلیسی (مثال: PCB)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='نام نمایشی برای کاربر (مثال: مشخصات PCB)', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/wrapper/image/')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='wrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wrappers', to='pcb.wrapper'),
        ),
    ]
