# Generated by Django 5.2.7 on 2026-07-10 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0018_wrapper_attributegroup_wrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegroup',
            name='wrapper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attribute_groups', to='pcb.wrapper'),
        ),
    ]
