# Generated by Django 5.2.7 on 2026-07-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0020_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
    ]
