# Generated by Django 5.2.7 on 2026-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0021_alter_faq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='control_type',
            field=models.CharField(choices=[('text_input', 'ورودی متنی/عددی'), ('radio_button', 'دکمه رادیویی'), ('select_box', 'لیست کشویی'), ('color_picker', 'انتخابگر رنگ'), ('multi_input', 'ورودی چندگانه')], default='radio_button', max_length=20, verbose_name='نوع کنترل در فرم'),
        ),
    ]
