# Generated by Django 5.2.7 on 2026-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0022_alter_attribute_control_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='unit',
            field=models.CharField(choices=[('', 'noting'), ('mm', 'mm'), ('inch', 'inch'), ('cm', 'cm'), ('pcs', 'pcs')], default=''),
        ),
    ]
