# Generated by Django 5.2.7 on 2026-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0023_attributeoption_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'noting'), ('mm', 'mm'), ('inch', 'inch'), ('cm', 'cm'), ('pcs', 'pcs')], default=''),
        ),
    ]
