# Generated by Django 5.2.7 on 2026-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0024_alter_attributeoption_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='unit',
        ),
    ]
