# Generated by Django 5.2.7 on 2026-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0025_unit_remove_attributeoption_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='unit',
            field=models.ManyToManyField(to='pcb.unit'),
        ),
    ]
