# Generated by Django 5.2.7 on 2026-07-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0026_attributeoption_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='pcb.unit'),
        ),
    ]
