# Generated by Django 5.2.7 on 2026-07-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0027_alter_attributeoption_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributeoption',
            name='unit',
        ),
    ]
