# Generated by Django 5.2.7 on 2026-07-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0028_remove_attributeoption_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='pcb.unit'),
        ),
    ]
