# Generated by Django 5.2.7 on 2026-07-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcb', '0029_attribute_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='control_type',
            field=models.CharField(choices=[('text_input', 'ورودی متنی/عددی'), ('radio_button', 'دکمه رادیویی'), ('select_box', 'لیست کشویی'), ('color_picker', 'انتخابگر رنگ'), ('multi_text_input', 'ورودی متن چندگانه')], default='radio_button', max_length=20, verbose_name='نوع کنترل در فرم'),
        ),
    ]
