# Generated by Django 5.2.7 on 2026-06-19 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/%Y/%m/', verbose_name='فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام فایل')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع فایل')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticketattachment_created', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticketattachment_edited', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage')),
            ],
            options={
                'verbose_name': 'پیوست تیکت',
                'verbose_name_plural': 'پیوست\u200cهای تیکت',
                'ordering': ['create_date'],
            },
        ),
    ]
