# Generated by Django 5.2.7 on 2026-06-19 13:56

import support.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(storage=support.storages.protected_media_storage, upload_to='ticket_attachments/%Y/%m/', verbose_name='فایل'),
        ),
    ]
