# Generated by Django 5.2.7 on 2026-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_guid_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('from_date', models.DateTimeField(verbose_name='نمایش از تاریخ:')),
                ('to_date', models.DateTimeField(verbose_name='نمایش تا تاریخ')),
            ],
        ),
    ]
