# Generated by Django 5.2.7 on 2026-07-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_hero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='WhyUs',
        ),
    ]
