# Generated by Django 5.2.7 on 2026-06-19 11:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', code='invalid_postal_code', message='کد پستی باید ۱۰ رقم باشد')], verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='نشانی کامل')),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام گیرنده')),
                ('receiver_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', code='invalid_phone', message='تلفن نا معتبر')], verbose_name='تلفن گیرنده')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_created', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_edited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='نام شرکت')),
                ('national_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', code='invalid_national_id', message='شناسه ملی باید ۱۱ رقم باشد')], verbose_name='شناسه ملی')),
                ('economic_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد اقتصادی')),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثبت')),
                ('legal_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت')),
                ('legal_address', models.TextField(blank=True, null=True, verbose_name='نشانی قانونی')),
                ('rep_full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی نماینده')),
                ('rep_national_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', code='invalid_national_code', message='کد ملی باید ۱۰ رقم باشد')], verbose_name='کد ملی نماینده')),
                ('rep_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', code='invalid_phone', message='تلفن نا معتبر')], verbose_name='تلفن نماینده')),
                ('rep_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='سمت نماینده')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('creator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legalprofile_created', to=settings.AUTH_USER_MODEL)),
                ('editor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='legalprofile_edited', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل حقوقی',
                'verbose_name_plural': 'پروفایل\u200cهای حقوقی',
            },
        ),
    ]
