from decimal import Decimal, ROUND_HALF_UP

DEFAULT_MONEY_PRECISION = Decimal("0.0001")
DEFAULT_RATE_PRECISION = Decimal("0.00000001")
DEFAULT_PERCENTAGE_PRECISION = Decimal("0.0001")

DEFAULT_ROUNDING = ROUND_HALF_UP